version: "2"
services:
  pmmp:
    ports:
     - "19132:19132"
     - "19132:19132/udp"
    image: grihabor/pmmp:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     - PM_LANG=eng
    restart: on-failure
    volumes:
     - pmmp_players:/pocketmine/players"
     - pmmp_worlds:/pocketmine/worlds"
     - pmmp_resource_packs:/pocketmine/resource_packs"
     - pmmp_plugins:/pocketmine/plugins"
    
volumes:
  pmmp_players:
    external: true
  pmmp_plugins:
    external: true
  pmmp_resource_packs:
    external: true
  pmmp_worlds:
    external: true

