version: "2"
services:
  pmmp:
    ports:
     - "19132:19132"
     - "19132:19132/udp"
    image: grihabor/pmmp:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     - PM_LANG=eng
    restart: on-failure
    volumes:
     - "${DIR_PLAYERS}:/pocketmine/players"
     - "${DIR_WORLDS}:/pocketmine/worlds"
     - "${DIR_RESOURCE_PACKS}:/pocketmine/resource_packs"
     - "${DIR_PLUGINS}:/pocketmine/plugins"
    
