version: "2"
services:
  pocketmine:
    ports:
     - "19132:19132"
     - "19132:19132/udp"
    image: grihabor/pocketmine
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PM_LANG=eng
    restart: on-failure
    volumes:
     - ../data//players:/pocketmine/players
     - ../data/worlds:/pocketmine/worlds
     - ../data/resource_packs:/pocketmine/resource_packs
     - ../data/plugins:/pocketmine/plugins
    
    
