all: up_build

up:
	docker-compose up

build:
	docker-compose build

up_build:
	docker-compose up --build

down:
	docker-compose down

force:
	docker-compose up --force

run:
	docker-compose run pmmp
